### ISSUE TITLE
Issue was removed

### ISSUE THREAD

**Issue by Yapperyapps** [Just-Some-Bots/ModTools#48]
Why did you remove my issue for the bot sending an error when I type !play <title> I need this fixed cause its the only working bot that I can actually control. Don't remove my issue until this has been fixed if you don't remember the error coded I posted thats your fault for removing the issue the first time

**Comment by jaydenkieran** [comment]
Your issue wasn't removed it was closed. If you actually read my comment, you'll see that you're in the wrong repository. This is **not** the MusicBot repository. I linked you to the correct issue for this problem in the MusicBot repo in my response to you.

If you make further issues here relating to MusicBot rather than this repo, you will be blocked from making further issues here, and potentially across every repo within our organisation. I've given you a clear solution.
